### ISSUE TITLE
Property [$numberOfPaginatorsRendered] not found on component: [company-table]

### ISSUE THREAD

**Issue by roomdada** [luckykenlin/livewire-tables#18]
Hello everyone, i need help to fix this bug.
![image](https://github.com/luckykenlin/livewire-tables/assets/61591337/0fe55a1f-3050-48ec-9c31-fc53aa7ee9ef)

**Comment by luckykenlin** [comment]
Hi, @roomdada ,

Have you tried to clear the cache?

```
php artisan clear-compiled &&
php artisan cache:clear &&
php artisan route:clear &&
php artisan view:clear &&
php artisan config:clear &&
composer dumpautoload -o
```

if the issue still happens, a mini-repo will be helpful.
